name: Deploy Laravel Sail (Remote)
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Despliegue de web
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USUARIO }}
          password:  ${{ secrets.PASS }}
          script: |
            set -e
            cd /var/www/Proyecto2DAW_AyoubAmmari_LucianoRovere/
            git pull
            cd ./bellreguard/
            php artisan migrate --force
            npm run build
